apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: pet-clinicapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-clinicapp
  template:
    metadata:
      labels:
        app: pet-clinicapp
    spec:
      containers:
      - name: pet-container
        image: deepikaarjunan/pet-clinic:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: pet-clinicapp
spec:
  selector:
    app: pet-clinicapp

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
